export enum Manufacturer {
    None = 0,
    Ford = 1,
    Mitsubishi = 2,
    Pagani = 3,
    BMW = 4,
    Bugatti = 5,
    Chevrolet = 6,
    Koenigsegg = 7,
    Lotus = 8,
    Mazda = 9,
    Mclaren = 10,
    Mercedes = 11,
    MMX = 12,
    Nissan = 13,
    P11 = 14,
    Pontiac = 15,
    RUF = 16,
    Subaru = 17,
    Drakart = 18,
    Ariel = 19,
    Tatum = 20
}